### ISSUE TITLE
Incorrect ground truth in the PBR dataset?

### ISSUE THREAD

**Issue by angshine** [thodan/bop_toolkit#33] opened 2020-05-13 05:07 UTC
I'm using the [PBR dataset](https://thodan.github.io/objectsynth/) to train an pose estimation network. I use the depth map and gt pose to calculate each object's coordinate map, however it leads to incorrect result. Then, I plot the object model recovered from the depth map and gt pose and the gt object model (.ply) in point cloud format. The plot shows that the recovered model and the gt model is not aligned.

The following is the code I use to plot the point cloud:
```
import numpy as np
import open3d as o3d
from bop_toolkit import inout
from numpy.linalg import inv

obj_id = ...  # label of one object in the image (the object to plot)
gt_R_m2cs = ... # gt_R_m2cs for objects in one image  - (n_obj, 3, 3)
gt_t_m2cs = ... # (n_obj, 3, 1)
gt_labels = ...  # labels for objects in one image (n_obj, )  --  start from 1
cam_K = ... # (3, 3) - the camera's intrinsic matrix
rgb_path = "path of the rgb image"
sem_path = "semantic segmentation path"
sem_map =inout.load_im(sem_path)
depth_path = "depth map path"
depth_map = inout.load_depth(depth_path)
d_map = depth_map  # (H, W)
H, W = d_map.shape
xy = np.array(np.meshgrid(range(W), range(H), indexing='xy'), dtype=np.float)  # (2, H, W)
xyz = np.concatenate((xy * d_map[None, ...], d_map[None, ...]), axis=0)  # (3, H, W)
XYZ = (inv(cam_K) @ xyz.reshape(3, -1)).T.reshape(H, W, 3)
obj_mask = sem_map==obj_id
XYZ_obj = XYZ[obj_mask, :]  # (n, 3)
R_m2c = gt_R_m2cs[gt_labels==obj_id, :][0]
t_m2c = gt_t_m2cs[gt_labels==obj_id, :][0]
# recovered_obj = (inv(R_m2c) @ (XYZ_obj.T - t_m2c)).T  # (n, 3)
recovered_obj = np.linalg.solve(R_m2c, XYZ_obj.T - t_m2c).T

ptcd = o3d.geometry.PointCloud()
ptcd.points = o3d.utility.Vector3dVector(recovered_obj)
ptcd.paint_uniform_color([255, 0, 0])   # paint recovered model with red
# original model
base_model_path = ".../BOP/lm/models/obj_{cls_id:06d}.ply"
model_path = base_model_path.format(cls_id=obj_id)
model = ObjectModel(model_path)   # read the point cloud from .ply file

o3d.visualization.draw_geometries([ptcd, model.ptcd])
```

Take a cat in one image as an example:
![Screenshot from 2020-05-13 12-59-25](https://user-images.githubusercontent.com/23130908/81772908-a13be700-9519-11ea-975b-8835839f9d16.png)

If I use the same code to plot the recovered model using datas in BOP's LM test set, the recovered model is aligned with the gt model.

---
Transform 3d model to the camera coordinate with gt poses, plot together with scene recovered by depth map:
![Screenshot from 2020-05-13 15-03-23](https://user-images.githubusercontent.com/23130908/81783930-afe0c900-952e-11ea-965a-2f298cb57298.png)

**Comment by thodan** [comment] 2020-05-13 11:53
Hello. I've double-checked the GT poses provided with the PBR dataset and haven't found any problem (the 3D object models are aligned with the image when rendered in the GT 6D poses). Please provide a minimal working example (ideally a zip archive including the code and all sample inputs).

**Comment by angshine** [comment] 2020-05-13 18:43
Thanks for your help. I wrote a small script to reproduce the result and took one data sample from the PBR scene 1. The following zip file should be enough to reproduce this issue.
[pbr_issue.zip](https://github.com/thodan/bop_toolkit/files/4623983/pbr_issue.zip)

**Comment by DC1991** [comment] 2020-06-04 09:17
Hi angshine,

Did you solve the problem? I met the same problem when rendering the 3D model to the scene by using the code in this git. I am debugging now, however, I still don't know how to address this.

**Comment by DC1991** [comment] 2020-06-04 10:35
I solved the problem, the problem is that for different images the camera parameters are different.  I wrongly thought they are the same for all images. But I do not know why camera parameters change for different images? Don't they fixed?

**Comment by thodan** [comment] 2020-06-05 08:46
Please see the description of the BOP format for an explanation of why the
camera parameters are not always fixed in the BOP datasets:
https://github.com/thodan/bop_toolkit/blob/master/docs/bop_datasets_format.md#camera-parameters

**Comment by angshine** [comment] 2020-06-05 10:32
@thodan I think I'm using the correct intrinsic parameters. I tried to generate objects' coordinate map by back projecting depth map to the object coordinate system and met the above problem. However,  I can generate the correct object coordinate map by rendering the object model. So I think the gt object pose is correct but there might be some problem with the gt depth map of PBR Dataset?

**Comment by thodan** [comment] 2020-06-17 14:34
@angshine Sorry, I am busy these weeks. Before I have a closer look at this issue, please check out the photorealistic images provided in the BOP Challenge 2020 (https://bop.felk.cvut.cz/challenges/bop-challenge-2020/). Those should do the job for you as well!

**Comment by angshine** [comment] 2020-06-17 15:41
@thodan Thanks for the new tools. I've started using the new PBR data.

**Closed** 2021-01-16 07:55 UTC

**Comment by psclklnk** [comment] 2021-07-01 11:50
I recently stumbled upon this thread because I faced the same problems with non-aligned objects and models, however could not find an answer here. Playing around a bit with different transformations from image- to camera coordinates I could at least solve my problem for the PBR and MSR datasets of the linemod objects. 

Indeed the problem seems to be in the depth maps, which have (or don't have) certain distortions depending on the dataset. Because of this different behavior of the depth maps, I needed different image to camera transformations. For the PBR rendered images, I required:

cam_coords = np.stack([(im_x - c_intr[0, 2]) * depths / c_intr[0, 0],
                                          (im_y - c_intr[1, 2]) * depths / c_intr[1, 1],
                                           depths], axis=-1)

where **im_x** and **im_y** are vectors containing the image coordinates and **depths** are the depth measurements at the corresponding pixels (already multiplied by the depth_scale factor). **c_intr** is the camera intrinsics matrix. For the MSR renderings of the linemod objects, I however required

xoz = (im_x - c_intr[0, 2]) / c_intr[0, 0]
yoz = (im_y - c_intr[1, 2]) / c_intr[1, 1]
z = depths / np.sqrt(1 + (xoz ** 2) + (yoz ** 2))
cam_coords = np.stack([xoz * z, yoz * z, z], axis=1).

We see that the difference is a non-linear scaling of the depth measurements depending on the position of the measurement in the image. Since I am still relatively new to the field of pose estimation and have not an extensive working knowledge I would need to check myself whether the first or the second way of computing the camera coordinates is the one that you obtain from assuming the standard pinhole camera model.

@thodan Can you maybe give additional insights into the differences between the depth maps? In any case thank you very much for this awesome toolkit, the collection of datasets and the corresponding challenge. It really helped me get started with this topic.
