### ISSUE TITLE
Corrupted shards in huggingface MegaPose-GSO dataset

### ISSUE THREAD

**Issue by zuodexin** [thodan/bop_toolkit#132] opened 2024-08-15 01:45 UTC
According to this [issue](https://github.com/thodan/bop_toolkit/issues/96#issue-1868565726), this problem seems fixed, however I still found same files corrupted in [huggingface datasets](https://huggingface.co/datasets/bop-benchmark/datasets/tree/main/MegaPose-GSO)

**Comment by thodan** [comment] 2024-08-15 11:24
@zuodexin, could you please share IDs of shards that are corrupted?

**Comment by thodan** [comment] 2024-08-15 11:25
I see you mentioned in the other issue that the problem is with the same shard as before. I will close this issue, let's continue there.

**Closed by thodan** 2024-08-15 11:25 UTC
